In [23]:
import os
import sys

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim


In [7]:
tensor = torch.randn(3, 4, 2).permute(0, 2, 1)
tensor, tensor.shape, tensor.dtype, tensor.device

(tensor([[[-1.0086, -0.1969,  0.4743,  1.2332],
          [ 0.8735,  0.8753,  0.0528,  0.9843]],
 
         [[ 0.6155, -0.3092,  0.7226,  0.2468],
          [ 0.8574, -0.4524,  2.1020,  0.0915]],
 
         [[-0.4897,  0.7155, -1.6454,  0.0726],
          [-0.0483, -0.2290,  0.2160, -2.1783]]]),
 torch.Size([3, 2, 4]),
 torch.float32,
 device(type='cpu'))

In [8]:
mask = tensor > 0
mask, mask.shape, mask.dtype, mask.device

(tensor([[[False, False,  True,  True],
          [ True,  True,  True,  True]],
 
         [[ True, False,  True,  True],
          [ True, False,  True,  True]],
 
         [[False,  True, False,  True],
          [False, False,  True, False]]]),
 torch.Size([3, 2, 4]),
 torch.bool,
 device(type='cpu'))

In [9]:
valid_mask = mask.any(dim=0).any(dim=1)
valid_mask_index = torch.where(valid_mask)[0]
valid_mask_index

tensor([0, 1])

In [11]:
tensor[mask]

tensor([0.4743, 1.2332, 0.8735, 0.8753, 0.0528, 0.9843, 0.6155, 0.7226, 0.2468,
        0.8574, 2.1020, 0.0915, 0.7155, 0.0726, 0.2160])

In [10]:
tensor[valid_mask_index]

tensor([[[-1.0086, -0.1969,  0.4743,  1.2332],
         [ 0.8735,  0.8753,  0.0528,  0.9843]],

        [[ 0.6155, -0.3092,  0.7226,  0.2468],
         [ 0.8574, -0.4524,  2.1020,  0.0915]]])

In [29]:
import argparse
import sys
sys.path.append('../SNeMPhyVAE/scripts/')
from settings import initial_settings

In [31]:
initial_settings

{'sideral_scale': 1.0027379097096139,
 'bands': None,
 'reference_time': None,
 'time_window': 300,
 'time_pad': 100,
 'error_floor': 0.01,
 'time_sigma': 20.0,
 'color_sigma': 0.3,
 'magsys': 'ab',
 'zeropoint': 25.0,
 'min_wave': 3206.34,
 'max_wave': 10915.01,
 'spectrum_bins': 1838,
 'band_oversampling': 51,
 'max_redshift': 1.0,
 'batch_size': 64,
 'learning_rate': 0.001,
 'penalty': 0.001,
 'latent_size': 3,
 'encode_conv_architecture': [40, 80, 120, 160, 200, 200, 200],
 'encode_conv_dilations': [1, 2, 4, 8, 16, 32, 64],
 'encode_fullyconnected_architecture': [200],
 'encode_time_architecture': [200],
 'encode_latent_prepool_architecture': [200],
 'encode_latent_postpool_architecture': [200],
 'decode_architecture': [40, 80, 160, 300]}

In [33]:
parser = argparse.ArgumentParser()
parser.add_argument('--latent_size', type=int, default=3, help='Size of the latent space')
args = parser.parse_args(args=sys.argv[1:])

if args.latent_size is not None:
    initial_settings['latent_size'] = args.latent_size
    
print("Current latent size:", initial_settings['latent_size'])

usage: ipykernel_launcher.py [-h] [--latent_size LATENT_SIZE]
ipykernel_launcher.py: error: unrecognized arguments: --f=/run/user/1000/jupyter/runtime/kernel-v37656da4647f7bb97d10feb50986b4935ffe12ce4.json


SystemExit: 2

/home/jurados/SNeMPhyVAE/SNeMPhyVAE/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3707: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [13]:
import yaml

In [15]:
document = """
a: 1
b:
    - 2
    - 3
c:
    d: 4
    e: 5
"""

print(yaml.dump(yaml.load(document)))


TypeError: load() missing 1 required positional argument: 'Loader'